{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "OMS Log Message API",
    "description" : "This API is used to show to job log messages.",
    "termsOfService" : "",
    "contact" : {
      "name" : "Remain Software",
      "url" : "https://remainsoftware.com",
      "email" : "helpdesk@remainsoftware.com"
    },
    "license" : {
      "name" : "Remain Software Commercial License ",
      "url" : "https://remainsoftware.com/software-licensing"
    },
    "version" : "0.0.1",
    "x-restgeninfo" : {
      "server" : "https://plato.remainsoftware.com:45111/generator",
      "object" : "OMQRLH",
      "library" : "V17T0119",
      "srclibrary" : "V17T0119S",
      "file" : "OMSLogMessageAPI.json"
    }
  },
  "servers" : [ {
    "url" : "{protocol}://{host}:{port}/{library}/OMQRLH",
    "description" : "plato",
    "variables" : {
      "protocol" : {
        "description" : "Protocol",
        "default" : "https",
        "enum" : [ "https", "http" ]
      },
      "host" : {
        "description" : "The host serves the API.",
        "default" : "plato.remainsoftware.com"
      },
      "library" : {
        "description" : "The TD/OMS library.",
        "default" : "OMS"
      },
      "port" : {
        "description" : "The port to which the server is listening.",
        "default" : "45011"
      }
    }
  } ],
  "security" : [ {
    "JWT" : [ ]
  } ],
  "paths" : {
    "/getMessage" : {
      "summary" : "It will return the second level message.",
      "description" : "It will return the second level message.",
      "post" : {
        "summary" : "it will return the second level message.",
        "description" : "it will return the second level message.",
        "operationId" : "getMessage",
        "requestBody" : {
          "description" : "Post Method",
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/messageRequest"
              }
            }
          }
        },
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/messageResponse"
                }
              }
            }
          },
          "400" : {
            "description" : "Bad Request from Client",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/errorResponse"
                }
              }
            }
          },
          "401" : {
            "description" : "Not authorized",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/errorResponse"
                },
                "examples" : {
                  "response401" : {
                    "value" : null,
                    "$ref" : "#/components/examples/response401"
                  }
                }
              }
            }
          }
        },
        "callbacks" : { },
        "x-generate" : {
          "session" : false,
          "jwtlogin" : false,
          "suffix" : "03",
          "generate" : false
        }
      }
    },
    "/getLogHistory" : {
      "summary" : "Get the log history",
      "description" : "Get the log history",
      "post" : {
        "summary" : "Get the log history",
        "description" : "Get the log history",
        "operationId" : "getLogHistory",
        "requestBody" : {
          "description" : "Post Method",
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/logHistoryRequest"
              },
              "examples" : {
                "getLogHistoryRequest" : {
                  "summary" : "How to specify the get log history request input parameter value.",
                  "value" : {
                    "applicationCode" : "XMP",
                    "pagingDetails" : {
                      "pageNumber" : 1,
                      "pageSize" : 50
                    },
                    "filterRecords" : [ ],
                    "searchFlags" : {
                      "exactMatch" : "0",
                      "caseSensitive" : "0",
                      "isOROperator" : "0"
                    }
                  }
                }
              }
            }
          }
        },
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/logHistoryResponse"
                },
                "examples" : {
                  "getLoghistory" : {
                    "summary" : "Response to a successful API call.",
                    "value" : {
                      "status" : "*NORM",
                      "totalRecords" : 46555,
                      "jobLogsHistory" : [ {
                        "jobName" : "QZRCSRVS",
                        "jobNumber" : 620853.0,
                        "userIDOrUserClass" : "MISHD",
                        "requestNumber" : "",
                        "taskNumber" : "",
                        "releaseNumber" : "",
                        "incomeDate" : 1241223.0,
                        "incomeTime" : 33409.0,
                        "applicationCode" : "XMP"
                      }, {
                        "jobName" : "QZRCSRVS",
                        "jobNumber" : 620850.0,
                        "userIDOrUserClass" : "MISHD",
                        "requestNumber" : "",
                        "taskNumber" : "",
                        "releaseNumber" : "",
                        "incomeDate" : 1241223.0,
                        "incomeTime" : 33404.0,
                        "applicationCode" : "XMP"
                      }, {
                        "jobName" : "QZRCSRVS",
                        "jobNumber" : 615592.0,
                        "userIDOrUserClass" : "WIM",
                        "requestNumber" : "",
                        "taskNumber" : "",
                        "releaseNumber" : "",
                        "incomeDate" : 1241220.0,
                        "incomeTime" : 133404.0,
                        "applicationCode" : "XMP"
                      }, {
                        "jobName" : "QZRCSRVS",
                        "jobNumber" : 615589.0,
                        "userIDOrUserClass" : "WIM",
                        "requestNumber" : "",
                        "taskNumber" : "",
                        "releaseNumber" : "",
                        "incomeDate" : 1241220.0,
                        "incomeTime" : 133403.0,
                        "applicationCode" : "XMP"
                      }, {
                        "jobName" : "QZRCSRVS",
                        "jobNumber" : 615577.0,
                        "userIDOrUserClass" : "WIM",
                        "requestNumber" : "",
                        "taskNumber" : "XT0611",
                        "releaseNumber" : "",
                        "incomeDate" : 1241220.0,
                        "incomeTime" : 133326.0,
                        "applicationCode" : "XMP"
                      } ]
                    }
                  }
                }
              }
            }
          },
          "400" : {
            "description" : "Bad Request from Client",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/errorResponse"
                }
              }
            }
          },
          "401" : {
            "description" : "Not authorized",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/errorResponse"
                },
                "examples" : {
                  "response401" : {
                    "value" : null,
                    "$ref" : "#/components/examples/response401"
                  }
                }
              }
            }
          }
        },
        "callbacks" : { },
        "x-generate" : {
          "session" : false,
          "jwtlogin" : false,
          "suffix" : "01",
          "generate" : false
        }
      }
    },
    "/listMessages" : {
      "summary" : "Get the list of messages.",
      "description" : "Get the list of messages.",
      "post" : {
        "summary" : "List the messages where messageid starts with OTPXXXX.",
        "description" : "List the messages where messageid starts with OTPXXXX.",
        "operationId" : "listMessages",
        "requestBody" : {
          "description" : "Post Method",
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/messageListRequest"
              },
              "examples" : {
                "listMessagesRequest" : {
                  "summary" : "How to specify the list messages request input parameter value.",
                  "value" : {
                    "applicationCode" : "XMP",
                    "pagingDetails" : {
                      "pageNumber" : 1,
                      "pageSize" : 50
                    },
                    "userIDOrUserClass" : "WIM",
                    "jobName" : "QPADEV0002",
                    "jobNumber" : 408397,
                    "messageFilterRecords" : [ ],
                    "searchFlags" : {
                      "exactMatch" : "0",
                      "caseSensitive" : "0",
                      "isOROperator" : "0"
                    },
                    "relativeRecordNumber" : 0
                  }
                }
              }
            }
          },
          "required" : false
        },
        "responses" : {
          "200" : {
            "description" : "return code 200 response",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/messageListResponse"
                },
                "examples" : {
                  "listMessages200" : {
                    "summary" : "response to a successful API call.",
                    "value" : {
                      "status" : "*NORM",
                      "totalRecords" : 9,
                      "messageLists" : [ {
                        "messageText" : "This is a subsetted list.",
                        "messageId" : "SUB0001",
                        "startTime" : "120910",
                        "severityCode" : 0,
                        "messageFile" : "OMSMSG",
                        "startDate" : "1240305",
                        "messageData" : "",
                        "isParent" : false,
                        "relativeRecordNumber" : 703034,
                        "program" : "OMO004",
                        "applicationCode" : "XMP",
                        "applicationDescription" : "Core Comics Supplies Service"
                      }, {
                        "messageText" : "Action 60 for event 'task/add' completed normally.",
                        "messageId" : "OMQB604",
                        "startTime" : "121927",
                        "severityCode" : 0,
                        "messageFile" : "OMSAPI",
                        "startDate" : "1240305",
                        "messageData" : "60         task/add",
                        "isParent" : false,
                        "relativeRecordNumber" : 703045,
                        "program" : "OMQCHGEV",
                        "applicationCode" : "XMP",
                        "applicationDescription" : "Core Comics Supplies Service"
                      }, {
                        "messageText" : "Fix number XT0509 of application  added.",
                        "messageId" : "OMQ200D",
                        "startTime" : "121927",
                        "severityCode" : 10,
                        "messageFile" : "OMSAPI",
                        "startDate" : "1240305",
                        "messageData" : "                              XT0509    Issue saving in octo",
                        "isParent" : false,
                        "relativeRecordNumber" : 703046,
                        "program" : "OMQUSIFI",
                        "applicationCode" : "XMP",
                        "applicationDescription" : "Core Comics Supplies Service"
                      }, {
                        "messageText" : "Object *DETAIL, type *FILE added to Fix XT0509.",
                        "messageId" : "ERO0001",
                        "startTime" : "122022",
                        "severityCode" : 0,
                        "messageFile" : "OMSMSG",
                        "startDate" : "1240305",
                        "messageData" : "*DETAIL     *FILE    XT0509",
                        "isParent" : false,
                        "relativeRecordNumber" : 703048,
                        "program" : "OMO008",
                        "applicationCode" : "XMP",
                        "applicationDescription" : "Core Comics Supplies Service"
                      }, {
                        "messageText" : "Press F5 to refresh the screen.",
                        "messageId" : "KEY0001",
                        "startTime" : "122023",
                        "severityCode" : 0,
                        "messageFile" : "OMSMSG",
                        "startDate" : "1240305",
                        "messageData" : "",
                        "isParent" : false,
                        "relativeRecordNumber" : 703049,
                        "program" : "OMO005",
                        "applicationCode" : "XMP",
                        "applicationDescription" : "Core Comics Supplies Service"
                      }, {
                        "messageText" : "Object *DETAIL, type *FILE added to Fix XT0509.",
                        "messageId" : "ERO0001",
                        "startTime" : "122905",
                        "severityCode" : 0,
                        "messageFile" : "OMSMSG",
                        "startDate" : "1240305",
                        "messageData" : "*DETAIL     *FILE    XT0509",
                        "isParent" : false,
                        "relativeRecordNumber" : 703062,
                        "program" : "OMO008",
                        "applicationCode" : "XMP",
                        "applicationDescription" : "Core Comics Supplies Service"
                      }, {
                        "messageText" : "Press F5 to refresh the screen.",
                        "messageId" : "KEY0001",
                        "startTime" : "122905",
                        "severityCode" : 0,
                        "messageFile" : "OMSMSG",
                        "startDate" : "1240305",
                        "messageData" : "",
                        "isParent" : false,
                        "relativeRecordNumber" : 703063,
                        "program" : "OMO005",
                        "applicationCode" : "XMP",
                        "applicationDescription" : "Core Comics Supplies Service"
                      }, {
                        "messageText" : "Action 60 for event 'task/change' completed normally.",
                        "messageId" : "OMQB604",
                        "startTime" : "122954",
                        "severityCode" : 0,
                        "messageFile" : "OMSAPI",
                        "startDate" : "1240305",
                        "messageData" : "60         task/change",
                        "isParent" : false,
                        "relativeRecordNumber" : 703076,
                        "program" : "OMQCHGEV",
                        "applicationCode" : "XMP",
                        "applicationDescription" : "Core Comics Supplies Service"
                      }, {
                        "messageText" : "Program ended when the user pressed F12. Panel was not processed.",
                        "messageId" : "OMQ5008",
                        "startTime" : "123216",
                        "severityCode" : 0,
                        "messageFile" : "OMSAPI",
                        "startDate" : "1240305",
                        "messageData" : "",
                        "isParent" : false,
                        "relativeRecordNumber" : 703088,
                        "program" : "OMO005",
                        "applicationCode" : "XMP",
                        "applicationDescription" : "Core Comics Supplies Service"
                      } ]
                    }
                  }
                }
              }
            }
          },
          "400" : {
            "description" : "Bad Request from Client",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/errorResponse"
                }
              }
            }
          },
          "401" : {
            "description" : "Not authorized",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/errorResponse"
                },
                "examples" : {
                  "response401" : {
                    "value" : null,
                    "$ref" : "#/components/examples/response401"
                  }
                }
              }
            }
          }
        },
        "callbacks" : { },
        "x-generate" : {
          "session" : false,
          "jwtlogin" : false,
          "suffix" : "02",
          "generate" : false
        }
      }
    }
  },
  "components" : {
    "schemas" : {
      "extendedMessage" : {
        "type" : "object",
        "properties" : {
          "messageFile" : {
            "maxLength" : 10,
            "type" : "string",
            "description" : "The IBMi message file.",
            "example" : "OMSMSG"
          },
          "messageId" : {
            "maxLength" : 7,
            "type" : "string",
            "description" : "The IBMi message id.",
            "example" : "DUPXXXX"
          },
          "messageType" : {
            "maxLength" : 1,
            "type" : "string",
            "description" : "The IBMi message type.",
            "example" : "E"
          },
          "messageData" : {
            "maxLength" : 256,
            "type" : "string",
            "description" : "The IBMi message data.",
            "example" : "DUPXXXX"
          },
          "field" : {
            "maxLength" : 50,
            "type" : "string",
            "description" : "The error in field.",
            "example" : ""
          },
          "messageText" : {
            "maxLength" : 644,
            "type" : "string",
            "description" : "The human readable message text.",
            "example" : "The message id is not found."
          }
        }
      },
      "errorResponse" : {
        "type" : "object",
        "properties" : {
          "messages" : {
            "$ref" : "#/components/schemas/extendedMessage"
          },
          "status" : {
            "maxLength" : 5,
            "type" : "string",
            "description" : "It returns the status.",
            "example" : "*TERM"
          }
        }
      },
      "messageInfo" : {
        "type" : "object",
        "properties" : {
          "messageId" : {
            "maxLength" : 7,
            "type" : "string",
            "description" : "It will contain the message id."
          },
          "messageFile" : {
            "maxLength" : 10,
            "type" : "string",
            "description" : "It will contain the message file."
          },
          "messageData" : {
            "maxLength" : 256,
            "type" : "string",
            "description" : "It will contain the message data."
          }
        },
        "description" : "It will contain the message information."
      },
      "messageResponse" : {
        "type" : "object",
        "properties" : {
          "status" : {
            "maxLength" : 5,
            "type" : "string",
            "description" : "It contains the status.",
            "example" : "*NORM"
          },
          "messageText" : {
            "maxLength" : 256,
            "type" : "string",
            "description" : "This contains the message text.",
            "example" : "This is a subsetted list."
          },
          "cause" : {
            "maxLength" : 1024,
            "type" : "string",
            "description" : "This contains the message cause.",
            "example" : "The list was built using user defined selection data. This means that probably not all available information is displayed."
          },
          "recovery" : {
            "maxLength" : 1024,
            "type" : "string",
            "description" : "This contains the message recovery.",
            "example" : "None needed. This message is informational."
          },
          "severityCode" : {
            "maximum" : 10,
            "type" : "integer",
            "description" : "It contains the severity code.",
            "example" : 0
          }
        }
      },
      "logHistoryRequest" : {
        "type" : "object",
        "properties" : {
          "applicationCode" : {
            "maxLength" : 5,
            "type" : "string",
            "description" : "The application name."
          },
          "pagingDetails" : {
            "$ref" : "#/components/schemas/pagingDetails"
          },
          "filterRecords" : {
            "maxItems" : 50,
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/filterRecords"
            }
          },
          "searchFlags" : {
            "$ref" : "#/components/schemas/searchFlags"
          }
        }
      },
      "filterRecords" : {
        "type" : "object",
        "properties" : {
          "startDate" : {
            "maxLength" : 10,
            "type" : "string",
            "description" : "The start date in YYYY-MM-DD format."
          },
          "startTime" : {
            "maxLength" : 8,
            "type" : "string",
            "description" : "The start time HH:MM:SS format."
          },
          "taskNumber" : {
            "maxLength" : 10,
            "type" : "string",
            "description" : "The task number."
          },
          "requestNumber" : {
            "maxLength" : 10,
            "type" : "string",
            "description" : "The request number."
          },
          "releaseNumber" : {
            "maxLength" : 10,
            "type" : "string",
            "description" : "The release number."
          },
          "jobName" : {
            "maxLength" : 10,
            "type" : "string",
            "description" : "It contains the job name."
          },
          "userIDOrUserClass" : {
            "maxLength" : 10,
            "type" : "string",
            "description" : "It contains the user name."
          },
          "jobNumber" : {
            "maxLength" : 6,
            "type" : "string",
            "description" : "It contains the job number."
          }
        }
      },
      "logHistoryResponse" : {
        "type" : "object",
        "properties" : {
          "status" : {
            "maxLength" : 5,
            "type" : "string",
            "description" : "It returns the status."
          },
          "totalRecords" : {
            "maximum" : 10,
            "type" : "integer",
            "description" : "Return the total number of records."
          },
          "jobLogsHistory" : {
            "maxItems" : 50,
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/jobLogsHistory"
            }
          }
        },
        "description" : "It contains the DSPLOGOMS log."
      },
      "jobLogsHistory" : {
        "type" : "object",
        "properties" : {
          "jobName" : {
            "maxLength" : 10,
            "type" : "string",
            "description" : "It contains the job name."
          },
          "jobNumber" : {
            "maximum" : 6,
            "type" : "number",
            "description" : "It contains the job number."
          },
          "userIDOrUserClass" : {
            "maxLength" : 10,
            "type" : "string",
            "description" : "it contains the user name."
          },
          "requestNumber" : {
            "maxLength" : 10,
            "type" : "string",
            "description" : "It contains the request number."
          },
          "taskNumber" : {
            "maxLength" : 10,
            "type" : "string",
            "description" : "It contains the task number."
          },
          "releaseNumber" : {
            "maxLength" : 10,
            "type" : "string",
            "description" : "It contains the release number."
          },
          "incomeDate" : {
            "type" : "number",
            "description" : "Income Date.",
            "format" : "zoned(7:0)"
          },
          "incomeTime" : {
            "type" : "number",
            "description" : "Income time.",
            "format" : "zoned(6:0)"
          },
          "applicationCode" : {
            "maxLength" : 5,
            "type" : "string",
            "description" : "It contains the application code."
          }
        },
        "description" : "It contains the DSPLOGOMS log."
      },
      "messageListRequest" : {
        "type" : "object",
        "properties" : {
          "applicationCode" : {
            "maxLength" : 5,
            "type" : "string",
            "description" : "It contains the application Code."
          },
          "pagingDetails" : {
            "$ref" : "#/components/schemas/pagingDetails"
          },
          "userIDOrUserClass" : {
            "maxLength" : 10,
            "type" : "string",
            "description" : "It contains the user name."
          },
          "jobName" : {
            "maxLength" : 10,
            "type" : "string",
            "description" : "It contains the job name."
          },
          "jobNumber" : {
            "type" : "number",
            "description" : "It contains the job number.",
            "format" : "zoned(6:0)"
          },
          "messageFilterRecords" : {
            "maxItems" : 50,
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/messageFilterRecords"
            }
          },
          "searchFlags" : {
            "$ref" : "#/components/schemas/searchFlags"
          },
          "relativeRecordNumber" : {
            "maximum" : 10,
            "type" : "integer",
            "description" : "It will contain from relative record number."
          }
        },
        "description" : ""
      },
      "messageListResponse" : {
        "type" : "object",
        "properties" : {
          "status" : {
            "maxLength" : 5,
            "type" : "string",
            "description" : "It contains the status."
          },
          "totalRecords" : {
            "maximum" : 10,
            "type" : "integer",
            "description" : "The total number of message entries in the list. Divide this by 50 to get the number of pages."
          },
          "messageLists" : {
            "maxItems" : 50,
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/messageLists"
            }
          }
        },
        "description" : ""
      },
      "pagingDetails" : {
        "type" : "object",
        "properties" : {
          "pageNumber" : {
            "maximum" : 10,
            "type" : "integer",
            "description" : "The page number to view. If the file contains 100 records and you want 50 records back then you can specify the page number e.g. 1 to get records 1 to 50."
          },
          "pageSize" : {
            "maximum" : 10,
            "type" : "integer",
            "description" : "It contains the number of records to be returned."
          }
        }
      },
      "messageFilterRecords" : {
        "type" : "object",
        "properties" : {
          "messageTexts" : {
            "maxLength" : 256,
            "type" : "string",
            "description" : "This contains the message texts."
          },
          "messageId" : {
            "maxLength" : 7,
            "type" : "string",
            "description" : "It contains the message id."
          },
          "startTime" : {
            "maxLength" : 8,
            "type" : "string",
            "description" : "The start time HH:MM:SS format."
          },
          "startDate" : {
            "maxLength" : 10,
            "type" : "string",
            "description" : "The start date in YYYY-MM-DD format."
          },
          "severityCode" : {
            "maximum" : 10,
            "type" : "integer",
            "description" : "It contains severity code."
          }
        },
        "description" : ""
      },
      "messageLists" : {
        "type" : "object",
        "properties" : {
          "messageText" : {
            "maxLength" : 256,
            "type" : "string",
            "description" : "It contains the message text."
          },
          "messageId" : {
            "maxLength" : 7,
            "type" : "string",
            "description" : "it contains the message id."
          },
          "startTime" : {
            "maxLength" : 8,
            "type" : "string",
            "description" : "The start time HH:MM:SS format."
          },
          "severityCode" : {
            "maximum" : 10,
            "type" : "integer",
            "description" : "It contains the severity code."
          },
          "messageFile" : {
            "maxLength" : 10,
            "type" : "string",
            "description" : "It contains the message file."
          },
          "startDate" : {
            "maxLength" : 10,
            "type" : "string",
            "description" : "The start date in YYYY-MM-DD format."
          },
          "messageData" : {
            "maxLength" : 256,
            "type" : "string",
            "description" : "It contains the message data."
          },
          "isParent" : {
            "type" : "boolean",
            "description" : "If OTPXXXX message has subsequent message then return true else false.",
            "default" : false
          },
          "relativeRecordNumber" : {
            "maximum" : 10,
            "type" : "integer",
            "description" : "It contains the relative record number."
          },
          "program" : {
            "maxLength" : 10,
            "type" : "string",
            "description" : "It contains the program name."
          },
          "applicationCode" : {
            "maxLength" : 5,
            "type" : "string",
            "description" : "It contains the application code."
          },
          "applicationDescription" : {
            "maxLength" : 50,
            "type" : "string",
            "description" : "It contains the application descriptions."
          }
        },
        "description" : ""
      },
      "messageRequest" : {
        "type" : "object",
        "properties" : {
          "messageId" : {
            "maxLength" : 7,
            "type" : "string",
            "description" : "It contains the message id.",
            "example" : "SUB0001"
          },
          "messageFile" : {
            "maxLength" : 10,
            "type" : "string",
            "description" : "It contains the message file.",
            "example" : "OMSMSG"
          },
          "messageData" : {
            "type" : "string",
            "description" : "It contains the message data.",
            "example" : ""
          }
        },
        "description" : ""
      },
      "searchFlags" : {
        "type" : "object",
        "properties" : {
          "exactMatch" : {
            "maxLength" : 1,
            "type" : "string",
            "description" : "It will contain 0 = false and 1 = true."
          },
          "caseSensitive" : {
            "maxLength" : 1,
            "type" : "string",
            "description" : "It will contain 0 = false and 1 = true."
          },
          "isOROperator" : {
            "maxLength" : 1,
            "type" : "string",
            "description" : "It will contain 0 = false and 1 = true."
          }
        },
        "description" : "It contains the job information."
      }
    },
    "responses" : { },
    "examples" : {
      "response401" : {
        "summary" : "Not authorized.",
        "value" : {
          "messages" : {
            "messageFile" : "OMSAPI",
            "messageId" : "OMQF201",
            "messageType" : "E",
            "messageData" : "",
            "field" : "",
            "messageText" : "Unauthorized or expired token. Please login again."
          },
          "status" : "*TERM"
        }
      }
    },
    "securitySchemes" : {
      "JWT" : {
        "type" : "http",
        "description" : "The HTTP API Token",
        "scheme" : "bearer",
        "bearerFormat" : "JWT"
      }
    },
    "callbacks" : { }
  }
}
