{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "TD/OMS Source API",
    "description" : "This API is used to read and write source files.",
    "contact" : {
      "name" : "Remain Software",
      "url" : "https://remainsoftware.com",
      "email" : "info@remainsoftware.com"
    },
    "license" : {
      "name" : "Remain Software License",
      "url" : "https://remainsoftware.com/remain-api-studio-terms-and-conditions"
    },
    "version" : "0.0.1",
    "x-restgeninfo" : {
      "server" : "https://plato.remainsoftware.com:45111/generator",
      "library" : "V16T0189",
      "file" : "sourcefileAPI.json",
      "srclibrary" : "V16T0189S",
      "object" : "OMRSRC",
      "additionalBindingDirs" : "OMRESTUTIL"
    }
  },
  "servers" : [ {
    "url" : "{protocol}://{host}:{port}/{library}/OMRSRC",
    "description" : "Source service",
    "variables" : {
      "host" : {
        "default" : "plato.remainsoftware.com"
      },
      "library" : {
        "description" : "",
        "default" : "OMS"
      },
      "protocol" : {
        "description" : "Protocol",
        "default" : "https",
        "enum" : [ "https", "http" ]
      },
      "port" : {
        "description" : "",
        "default" : "45011"
      }
    }
  } ],
  "security" : [ {
    "jwt" : [ ]
  } ],
  "tags" : [ {
    "name" : "Source",
    "description" : "Source related operations"
  } ],
  "paths" : {
    "/object/get" : {
      "summary" : "Get the source from an object",
      "description" : "This returns the source from a TD/OMS Objects. It also passes the known references of this object.",
      "post" : {
        "summary" : "Retrieve the main source of the object",
        "description" : "Retrieve the main source of the object",
        "operationId" : "objectGet",
        "requestBody" : {
          "description" : "The object source request.",
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/sourceRequest"
              },
              "examples" : {
                "objectGet" : {
                  "value" : null,
                  "$ref" : "#/components/examples/getAnyMemberReadOnly"
                },
                "objectGet_IFS_Object" : {
                  "value" : null,
                  "$ref" : "#/components/examples/objectGet_IFS_Object"
                },
                "objectget_copybook" : {
                  "value" : null,
                  "$ref" : "#/components/examples/objectget_copybook"
                },
                "objectget" : {
                  "value" : null,
                  "$ref" : "#/components/examples/objectget"
                }
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/sourceReply"
                },
                "examples" : {
                  "response200" : {
                    "summary" : "Response to a successful API call.",
                    "value" : {
                      "canEdit" : true,
                      "sourceCode" : "",
                      "includes" : [ ],
                      "references" : [ ],
                      "ccsid" : 37,
                      "sourceType" : "CLLE",
                      "pageNumber" : 0,
                      "numberOfPages" : 1,
                      "maximumLineLength" : 80,
                      "lastChangeDate" : "2024-01-06-22.04.16.000000"
                    }
                  }
                }
              }
            }
          },
          "400" : {
            "description" : "Request not valid",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/extendedMessage"
                },
                "examples" : {
                  "response400" : {
                    "value" : null,
                    "$ref" : "#/components/examples/response400"
                  }
                }
              }
            }
          },
          "401" : {
            "description" : "Not Authorized",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/extendedMessage"
                },
                "examples" : {
                  "response401" : {
                    "value" : null,
                    "$ref" : "#/components/examples/response401"
                  }
                }
              }
            }
          }
        },
        "callbacks" : { },
        "x-generate" : {
          "session" : false,
          "jwtlogin" : false,
          "suffix" : "3",
          "generate" : false
        }
      }
    },
    "/object/save" : {
      "summary" : "Save the source which belongs to the object",
      "description" : "Save the source which belongs to the object",
      "post" : {
        "summary" : "Save the source which belongs to the object",
        "description" : "Save the source which belongs to the object",
        "operationId" : "objectSave",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/objectSaveRequest"
              },
              "examples" : {
                "objectSave_IFS_Object" : {
                  "value" : null,
                  "$ref" : "#/components/examples/objectSave_IFS_Object"
                },
                "objectSave_copybook" : {
                  "value" : null,
                  "$ref" : "#/components/examples/objectSave_copybook"
                },
                "objectSave" : {
                  "value" : null,
                  "$ref" : "#/components/examples/objectSave"
                }
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/extendedMessage"
                },
                "examples" : {
                  "response200" : {
                    "summary" : "Response to a successful API call.",
                    "value" : {
                      "messageFile" : "OMSAPI",
                      "messageId" : "OMQF209",
                      "messageType" : "",
                      "messageData" : "",
                      "field" : "",
                      "messageText" : "The source code saved successfully. &N Cause . . . . . :   The source code was saved successfully. Recovery: No recovery necessary. This is an informational message.",
                      "lastChangeDate" : "2024-10-09-06.52.40.000000"
                    }
                  }
                }
              }
            }
          },
          "400" : {
            "description" : "Request not valid",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/extendedMessage"
                },
                "examples" : {
                  "response400" : {
                    "value" : null,
                    "$ref" : "#/components/examples/response400"
                  }
                }
              }
            }
          },
          "401" : {
            "description" : "Not Authorized",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/extendedMessage"
                },
                "examples" : {
                  "response401" : {
                    "value" : null,
                    "$ref" : "#/components/examples/response401"
                  }
                }
              }
            }
          }
        },
        "callbacks" : { },
        "x-generate" : {
          "session" : false,
          "jwtlogin" : false,
          "suffix" : "2",
          "generate" : false
        }
      }
    }
  },
  "components" : {
    "schemas" : {
      "message" : {
        "type" : "object",
        "properties" : {
          "messageText" : {
            "maxLength" : 256,
            "type" : "string",
            "description" : "It contains the first level message text."
          },
          "messageID" : {
            "maxLength" : 50,
            "type" : "string",
            "description" : "It contains the message id of the message : Example - CPF0000"
          },
          "messageTextExtended" : {
            "maxLength" : 1024,
            "type" : "string",
            "description" : "It contains the additional message information based on the value of the request."
          },
          "messageFile" : {
            "type" : "string",
            "description" : "The message file"
          }
        },
        "description" : "message object"
      },
      "sourceRequest" : {
        "type" : "object",
        "properties" : {
          "applicationCode" : {
            "maxLength" : 5,
            "type" : "string",
            "description" : "The application code."
          },
          "taskNumber" : {
            "maxLength" : 10,
            "type" : "string",
            "description" : "The task number."
          },
          "path" : {
            "maxLength" : 1024,
            "type" : "string",
            "description" : "The location of the IFS file to read."
          },
          "objectCode" : {
            "maxLength" : 12,
            "type" : "string",
            "description" : "the object code"
          },
          "objectType" : {
            "maxLength" : 9,
            "type" : "string",
            "description" : "The object type"
          },
          "objectLibrary" : {
            "maxLength" : 10,
            "type" : "string",
            "description" : "The object library"
          },
          "memberCode" : {
            "maxLength" : 10,
            "type" : "string",
            "description" : "The member code"
          },
          "pageNumber" : {
            "type" : "integer",
            "description" : "The pagenumber to fetch. If not passed then the first page is fetched."
          }
        },
        "description" : "The request for a source",
        "x-pfname" : "OMOBJ",
        "x-library" : "V150KEP",
        "x-host" : "plato.remain.local"
      },
      "sourceReply" : {
        "type" : "object",
        "properties" : {
          "canEdit" : {
            "type" : "boolean",
            "description" : "True if the source can be saved back or false if it is view only."
          },
          "sourceCode" : {
            "maxLength" : 65535,
            "type" : "string",
            "description" : "The source code"
          },
          "includes" : {
            "maxItems" : 1024,
            "type" : "array",
            "description" : "Included sources like copybooks",
            "items" : {
              "$ref" : "#/components/schemas/ifsPath"
            }
          },
          "references" : {
            "maxItems" : 1024,
            "type" : "array",
            "description" : "An array of non source references",
            "items" : {
              "$ref" : "#/components/schemas/ifsPath"
            }
          },
          "ccsid" : {
            "type" : "integer",
            "description" : "The CCSID of the source on the IBM i"
          },
          "sourceType" : {
            "maxLength" : 10,
            "type" : "string",
            "description" : "This is the source type. Examples are RPGLE, SQL, etc.."
          },
          "pageNumber" : {
            "type" : "integer",
            "description" : "This is the page number."
          },
          "numberOfPages" : {
            "type" : "integer",
            "description" : "The total number of pages."
          },
          "maximumLineLength" : {
            "type" : "integer",
            "description" : "Source record fomat length"
          },
          "message" : {
            "$ref" : "#/components/schemas/extendedMessage"
          },
          "lastChangeDate" : {
            "maxLength" : 26,
            "type" : "string",
            "description" : "Last change date of source member in timestap format."
          }
        },
        "description" : "The reply to the source request"
      },
      "ifsPath" : {
        "type" : "object",
        "properties" : {
          "path" : {
            "maxLength" : 1024,
            "type" : "string",
            "description" : "The path of the object"
          }
        },
        "description" : "The path to an IFS object"
      },
      "objectSaveRequest" : {
        "type" : "object",
        "properties" : {
          "objectLibrary" : {
            "maxLength" : 10,
            "type" : "string",
            "description" : "The object library"
          },
          "memberCode" : {
            "maxLength" : 10,
            "type" : "string",
            "description" : "The member code"
          },
          "path" : {
            "maxLength" : 1024,
            "type" : "string",
            "description" : "The location of the IFS file to read."
          },
          "sourceCode" : {
            "maxLength" : 65535,
            "type" : "string",
            "description" : "The source code"
          },
          "objectCode" : {
            "maxLength" : 12,
            "type" : "string",
            "description" : "the object code"
          },
          "taskNumber" : {
            "maxLength" : 10,
            "type" : "string",
            "description" : "The task number."
          },
          "applicationCode" : {
            "maxLength" : 5,
            "type" : "string",
            "description" : "The application code."
          },
          "objectType" : {
            "maxLength" : 9,
            "type" : "string",
            "description" : "The object Type"
          },
          "ccsid" : {
            "type" : "integer",
            "description" : "The CCSID of the source on the IBM i"
          },
          "pageNumber" : {
            "type" : "integer",
            "description" : "The current pagenumber of 1 megabyte source pages"
          },
          "numberOfPages" : {
            "type" : "integer",
            "description" : "The total number of pages."
          },
          "forceSave" : {
            "type" : "boolean",
            "description" : "true - Save the source.\r\nfalse - Don't save the source if source member is recently changed.",
            "default" : false
          },
          "lastChangeDate" : {
            "type" : "string",
            "description" : "Last change date of source member in timestap format."
          }
        },
        "description" : "The request for save object",
        "x-pfname" : "OMOBJ",
        "x-host" : "plato.remain.local",
        "x-library" : "V150KEP"
      },
      "extendedMessage" : {
        "type" : "object",
        "properties" : {
          "messageFile" : {
            "maxLength" : 10,
            "type" : "string",
            "description" : "The IBMi message file."
          },
          "messageId" : {
            "maxLength" : 7,
            "type" : "string",
            "description" : "The message id."
          },
          "messageType" : {
            "maxLength" : 1,
            "type" : "string",
            "description" : "The message type,"
          },
          "messageData" : {
            "maxLength" : 80,
            "type" : "string",
            "description" : "The message substitution data."
          },
          "field" : {
            "maxLength" : 10,
            "type" : "string",
            "description" : "The field in error."
          },
          "messageText" : {
            "maxLength" : 512,
            "type" : "string",
            "description" : "The human redable text."
          },
          "lastChangeDate" : {
            "maxLength" : 26,
            "type" : "string",
            "description" : "Last change date of source member in timestap format."
          }
        }
      }
    },
    "responses" : { },
    "parameters" : { },
    "examples" : {
      "objectget_copybook" : {
        "summary" : "Get a member that is attached to a task",
        "description" : "If the member is in development on the task, you can get it in change mode. Specify zero for the pageNumber to get only information about the member and not the source itself.",
        "value" : {
          "objectLibrary" : "IRESTLIB",
          "memberCode" : "OMHLPDS",
          "objectCode" : "QCPYLESRC",
          "pageNumber" : 1,
          "taskNumber" : "XT0497",
          "applicationCode" : "XMP",
          "objectType" : "*FILE"
        }
      },
      "objectSave_copybook" : {
        "summary" : "Save a source member",
        "description" : "Make sure to return the last change date that you got from the read request. This allows us to detect if a source was changed by someone else.",
        "value" : {
          "objectLibrary" : "IRESTLIB",
          "memberCode" : "OMHLPDS",
          "sourceCode" : "CAgRCAgRDhDVEZQICAgIC...CA3NQ0KICAgICBEICBEOENURkwgICA",
          "objectCode" : "QCPYLESRC",
          "pageNumber" : 1,
          "numberOfPages" : 1,
          "lastChangeDate" : "2018-12-03-12.07.15.000000",
          "taskNumber" : "XT0497",
          "forceSave" : false,
          "applicationCode" : "XMP",
          "objectType" : "*FILE",
          "ccsid" : 37
        }
      },
      "objectSave" : {
        "summary" : "Save an object source",
        "description" : "",
        "value" : {
          "objectLibrary" : "O_XT0497D",
          "memberCode" : "",
          "sourceCode" : "cGdtICAgI...A0KDQplbmRwZ20NCg==",
          "objectCode" : "BAS",
          "pageNumber" : 1,
          "numberOfPages" : 1,
          "lastChangeDate" : "2024-01-06-22.04.16.000000",
          "taskNumber" : "XT0497",
          "forceSave" : false,
          "applicationCode" : "XMP",
          "objectType" : "*PGM",
          "ccsid" : 37
        }
      },
      "objectSave_IFS_Object" : {
        "summary" : "Save an IFS source",
        "description" : "Specify zero for the pageNumber to get only information about the member and not the source itself.",
        "value" : {
          "path" : "/QOpenSys/OMSIFS/XMP/DEV/PHP_XT0497/htdocs/public/js/dashboard.js",
          "sourceCode" : "JChmdW5jdGlvbigpIH...C8vIExvYWQgdGhlIFZpc",
          "pageNumber" : 1,
          "numberOfPages" : 1,
          "lastChangeDate" : "",
          "taskNumber" : "XT0497",
          "forceSave" : false,
          "applicationCode" : "XMP",
          "ccsid" : 1208
        }
      },
      "objectGet_IFS_Object" : {
        "summary" : "Read an IFS source",
        "description" : "Specify zero for the pageNumber to get only information about the member and not the source.",
        "value" : {
          "path" : "/QOpenSys/OMSIFS/XMP/DEV/PHP_XT0497/htdocs/public/js/dashboard.js",
          "pageNumber" : 1,
          "taskNumber" : "XT0497",
          "applicationCode" : "XMP"
        }
      },
      "objectget" : {
        "summary" : "Read the source of an object,",
        "description" : "Specify zero for the pageNumber to get only information about the member and not the source itself.",
        "value" : {
          "objectLibrary" : "O_XT0497D",
          "memberCode" : "",
          "objectCode" : "BAS",
          "pageNumber" : 1,
          "taskNumber" : "XT0497",
          "applicationCode" : "XMP",
          "objectType" : "*PGM"
        }
      },
      "getAnyMemberReadOnly" : {
        "summary" : "Get any member read only",
        "description" : "This does not contain an application or task. So this member will be fetched if it exists as read only. Specify zero for the pageNumber to get only information about the member and not the source.",
        "value" : {
          "objectLibrary" : "V170DMP",
          "memberCode" : "DMP0001365",
          "objectCode" : "QRPGLESRC",
          "pageNumber" : 1,
          "objectType" : "*FILE"
        }
      },
      "response401" : {
        "summary" : "Not authorized.",
        "value" : {
          "messageFile" : "OMSAPI",
          "messageId" : "OMQF201",
          "messageType" : "",
          "messageData" : "",
          "field" : "",
          "messageText" : "Unauthorized or expired token. Please login again."
        }
      },
      "response400" : {
        "summary" : "Something went wrong.",
        "value" : {
          "messageFile" : "OMSAPI",
          "messageId" : "OMQB325",
          "messageType" : "E",
          "messageData" : "xxxxx       *PGM     *N",
          "field" : "",
          "messageText" : "Object xxxxx type *PGM detail *N not found. &N Cause . . . . . :   The requested action for object xxxxx type *PGM detail *N could not be done because the detail or the object was not found. If the detail is *N then the object was not found. &N Recovery  . . . :   Add the detail and try your request again."
        }
      }
    },
    "requestBodies" : { },
    "securitySchemes" : {
      "jwt" : {
        "type" : "http",
        "description" : "JWT Token",
        "scheme" : "bearer",
        "bearerFormat" : "JWT"
      }
    },
    "callbacks" : { }
  }
}
